package main

import (
	"context"
	"fmt"
	"net/http"
	"os"

	"github.com/gameplan-backend/api"
	"github.com/gameplan-backend/api_server"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echomiddleware "github.com/oapi-codegen/echo-middleware"
	"github.com/stytchauth/stytch-go/v16/stytch/consumer/stytchapi"
)

func main() {
	e := echo.New()

	// Middleware
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())

	// Load and validate OpenAPI spec
	swagger, err := openapi3.NewLoader().LoadFromFile("openapi.yml")
	if err != nil {
		e.Logger.Fatal("Failed to load OpenAPI spec:", err)
	}
	if err := swagger.Validate(context.Background()); err != nil {
		e.Logger.Fatal("OpenAPI spec validation failed:", err)
	}

	// Add OpenAPI validator middleware
	e.Use(echomiddleware.OapiRequestValidator(swagger))

	// Initialize Stytch client
	stytchProjectID := os.Getenv("STYTCH_PROJECT_ID")
	stytchSecret := os.Getenv("STYTCH_SECRET")
	if stytchProjectID == "" || stytchSecret == "" {
		panic("STYTCH_PROJECT_ID and STYTCH_SECRET environment variables must be set")
	}

	stytchClient, err := stytchapi.NewClient(
		stytchProjectID,
		stytchSecret,
	)
	if err != nil {
		panic(err)
	}

	// Create the API implementation
	myApi := &api_server.MyApiServer{StytchClient: stytchClient}

	// Authentication middleware
	e.Use(api.AuthMiddleware(stytchClient))

	// Register the strict handlers generated by oapi-codegen
	strictHandler := api.NewStrictHandler(myApi, nil)
	api.RegisterHandlers(e, strictHandler)

	// Start server
	port := "8080"
	fmt.Printf("Starting server on port %s...\n", port)
	if err := e.Start(":" + port); err != nil && err != http.ErrServerClosed {
		e.Logger.Fatal(err)
	}
}
