schemas:
  DbPlayer:
    type: object
    properties:
      id:
        type: integer
      userId:
        type: integer
      name:
        type: string
      email:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      preferredMatchGroup:
        type: integer
        nullable: true
      isActive:
        type: boolean
      emailNotificationsEnabled:
        type: boolean
    required:
      - id
      - userId
      - name
      - email
      - createdAt
      - updatedAt
      - preferredMatchGroup
      - isActive
      - emailNotificationsEnabled

  DbPlayerCustomColumn:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      field_type:
        type: string
      description:
        type: string
      is_required:
        type: boolean
      is_active:
        type: boolean
      display_order:
        type: integer
    required:
      - id
      - name
      - field_type
      - description
      - is_required
      - is_active
      - display_order

  DbPlayerCustomValue:
    type: object
    properties:
      id:
        type: integer
      playerId:
        type: integer
      columnId:
        type: integer
      value:
        type: string
    required:
      - id
      - playerId
      - columnId
      - value
  DbSeason:
    type: object
    properties:
      id:
        type: integer
      userId:
        type: integer
      name:
        type: string
      startDate:
        type: string
        format: date
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      isActive:
        type: boolean
      seasonType:
        type: string
        enum:
          - pool
          - bowling
          - other
      frequency:
        type: string
        enum:
          - weekly
          - biweekly
          - monthly
          - quarterly
          - yearly
    required:
      - id
      - userId
      - name
      - startDate
      - createdAt
      - updatedAt
      - isActive
      - seasonType
      - frequency
      - value
  DbMatch:
    type: object
    properties:
      id:
        type: integer
      seasonId:
        type: integer
      playerId1:
        type: integer
      playerId2:
        type: integer
      playerId1Points:
        type: integer
      playerId2Points:
        type: integer
      matchDate:
        type: string
        format: date
      group:
        type: integer
    required:
      - id
      - seasonId
      - playerId1
      - playerId2
      - playerId1Points
      - playerId2Points
      - matchDate
      - group

  DbMatchCustomColumn:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
    required:
      - id
      - name

  DbMatchCustomValue:
    type: object
    properties:
      id:
        type: integer
      matchId:
        type: integer
      columnId:
        type: integer
      value:
        type: string
    required:
      - id
      - matchId
      - columnId
      - value
  AddMatchParams:
    type: object
    properties:
      seasonId:
        type: integer
      playerId1:
        type: integer
      playerId2:
        type: integer
      matchDate:
        type: string
        format: date
    required:
      - seasonId
      - playerId1
      - playerId2
      - matchDate

  SaveMatchDataParams:
    type: object
    properties:
      matchId:
        type: integer
      key:
        type: string
      value:
        type: object
    required:
      - matchId
      - key
      - value

  UnassignPlayerFromMatchParams:
    type: object
    properties:
      playerId:
        type: integer
      matchId:
        type: integer
    required:
      - playerId
      - matchId

  CreatePoolPlayerParams:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
      emailNotificationsEnabled:
        type: boolean
    required:
      - name
      - email
      - emailNotificationsEnabled

  CreatePlayerCustomColumnParams:
    type: object
    properties:
      name:
        type: string
      fieldType:
        type: string
        enum:
          - text
          - number
          - date
          - boolean
          - select
      description:
        type: string
      isRequired:
        type: boolean
      displayOrder:
        type: integer
    required:
      - name
      - fieldType
      - description
      - isRequired
      - displayOrder

  SavePlayerCustomValueParams:
    type: object
    properties:
      playerId:
        type: integer
      columnId:
        type: integer
      value:
        type: string
    required:
      - playerId
      - columnId
      - value

  GetPlayersParams:
    type: object
    properties:
      limit:
        type: integer
      offset:
        type: integer
    required:
      - limit
      - offset

  SavePlayerDataParams:
    type: object
    properties:
      playerId:
        type: integer
      key:
        type: string
      value:
        type: object
    required:
      - playerId
      - key
      - value

  CreateSeasonParams:
    type: object
    properties:
      name:
        type: string
      startDate:
        type: string
        format: date
      amountOfTables:
        type: integer
      seasonType:
        type: string
      players:
        type: array
        items:
          type: integer
    required:
      - name
      - startDate
      - amountOfTables
      - seasonType
      - players

  UpdateSeasonParams:
    type: object
    properties:
      name:
        type: string
    required:
      - seasonId
      - name

  SendSupportMessageParams:
    type: object
    properties:
      content:
        type: string
      messageType:
        type: string
      from:
        type: string
    required:
      - content
      - messageType
      - from

  SignUpUserParams:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
      password:
        type: string
      confirmPassword:
        type: string
      phone:
        type: string
        nullable: true
      country:
        type: string
      lang:
        type: string
        enum:
          - fr
          - en
      birthday:
        type: string
        format: date
        nullable: true
      acceptTerms:
        type: boolean
    required:
      - name
      - email
      - password
      - confirmPassword
      - country
      - lang
      - acceptTerms

  LoginUserParams:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
      - email
      - password

  SendResetPasswordLinkParams:
    type: object
    properties:
      email:
        type: string
    required:
      - email

  ResetCurrentUserPasswordParams:
    type: object
    properties:
      newPassword:
        type: string
      token:
        type: string
      newPasswordConfirm:
        type: string
    required:
      - newPassword
      - token
      - newPasswordConfirm

  SaveUserSettingsParams:
    type: object
    properties:
      email:
        type: string
        nullable: true
      phone:
        type: string
        nullable: true
      name:
        type: string
        nullable: true
      lang:
        type: string
        nullable: true
      birthday:
        type: string
        format: date
        nullable: true

  UpdateUserPasswordParams:
    type: object
    properties:
      token:
        type: string
      password:
        type: string
      passwordConfirmation:
        type: string
    required:
      - token
      - password
      - passwordConfirmation

  SaveAppSettingsParams:
    type: object
    properties:
      settings:
        type: object # Assuming AppSettings is a complex object
    required:
      - settings

  ErrorResponse:
    type: object
    properties:
      code:
        type: string
