// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Match struct {
	ID              int32
	Seasonid        pgtype.Int4
	Playerid1       pgtype.Int4
	Playerid1points int32
	Playerid2       pgtype.Int4
	Playerid2points int32
	Matchdate       pgtype.Date
	Winnerid        pgtype.Int4
	Createdat       pgtype.Timestamp
	Updatedat       pgtype.Timestamp
	Isactive        bool
	Group           int32
}

type MatchCustomColumn struct {
	ID           int32
	Name         string
	FieldType    string
	Description  pgtype.Text
	IsRequired   pgtype.Bool
	IsActive     pgtype.Bool
	DisplayOrder pgtype.Int4
	Createdat    pgtype.Timestamp
	Updatedat    pgtype.Timestamp
}

type MatchCustomValue struct {
	ID        int32
	MatchID   pgtype.Int4
	ColumnID  pgtype.Int4
	Value     pgtype.Text
	Createdat pgtype.Timestamp
	Updatedat pgtype.Timestamp
}

type Player struct {
	ID                        int32
	Userid                    pgtype.Int4
	Name                      string
	Email                     pgtype.Text
	Createdat                 pgtype.Timestamp
	Updatedat                 pgtype.Timestamp
	Preferredmatchgroup       pgtype.Int4
	Isactive                  bool
	Emailnotificationsenabled bool
}

type PlayerCustomColumn struct {
	ID           int32
	Name         string
	FieldType    string
	Description  pgtype.Text
	IsRequired   pgtype.Bool
	IsActive     pgtype.Bool
	DisplayOrder pgtype.Int4
	Createdat    pgtype.Timestamp
	Updatedat    pgtype.Timestamp
}

type PlayerCustomValue struct {
	ID        int32
	PlayerID  pgtype.Int4
	ColumnID  pgtype.Int4
	Value     pgtype.Text
	Createdat pgtype.Timestamp
	Updatedat pgtype.Timestamp
}

type Season struct {
	ID         int32
	Userid     pgtype.Int4
	Name       string
	Startdate  pgtype.Date
	Createdat  pgtype.Timestamp
	Updatedat  pgtype.Timestamp
	Isactive   bool
	Seasontype string
	Frequency  string
}

type User struct {
	ID               int32
	Stytchid         string
	Stripeid         string
	Name             string
	Email            string
	Phone            pgtype.Text
	Country          pgtype.Text
	Birthday         pgtype.Int4
	Lang             string
	Createdat        pgtype.Timestamp
	Updatedat        pgtype.Timestamp
	Isactive         bool
	Isverified       bool
	Subscriptiontier string
	Jsonsettings     pgtype.Text
}
